// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABQ_Mi8SN6Bxzr0Uam1qRq8c5x5qv3eUU',
    appId: '1:465856595098:web:a91c07a760a3cd8b56cb23',
    messagingSenderId: '465856595098',
    projectId: 'authentication-all-firebase',
    authDomain: 'authentication-all-firebase.firebaseapp.com',
    storageBucket: 'authentication-all-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqCxGED3qPqvGkUWy-DG7DgSEJZxbdvho',
    appId: '1:465856595098:android:4c656d457f5edc2056cb23',
    messagingSenderId: '465856595098',
    projectId: 'authentication-all-firebase',
    storageBucket: 'authentication-all-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDhVGqfZ9n4ZYNfynMPFn4u0kw6zyVkLA',
    appId: '1:465856595098:ios:a41be30bc29b43ce56cb23',
    messagingSenderId: '465856595098',
    projectId: 'authentication-all-firebase',
    storageBucket: 'authentication-all-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDhVGqfZ9n4ZYNfynMPFn4u0kw6zyVkLA',
    appId: '1:465856595098:ios:a41be30bc29b43ce56cb23',
    messagingSenderId: '465856595098',
    projectId: 'authentication-all-firebase',
    storageBucket: 'authentication-all-firebase.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABQ_Mi8SN6Bxzr0Uam1qRq8c5x5qv3eUU',
    appId: '1:465856595098:web:f85d868f5c8d2a1456cb23',
    messagingSenderId: '465856595098',
    projectId: 'authentication-all-firebase',
    authDomain: 'authentication-all-firebase.firebaseapp.com',
    storageBucket: 'authentication-all-firebase.appspot.com',
  );
}
